# Generated by Django 5.0.4 on 2024-04-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nicole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='askquestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
