# Generated by Django 5.0.4 on 2024-04-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nicole', '0002_registration_askquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='askquestion',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='dateofbirth',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='phone_number',
        ),
    ]
